### ISSUE TITLE
Evaluation of SuperPoint on datasets

### ISSUE THREAD

**Issue by yakult98** [rpautrat/LISRD#10]
Sorry to bother you,
I have evaluated the pertrained models on HPatches and RDNIM datasets already. 
If I want to compare the performance of SuperPoint on these datasets, how can I do it? Could you give me some details?
Thanks!

**Comment by rpautrat** [comment]
Hi, similarly as for LISRD and its `export_features.py`, you can do the same with the [official repo of SuperPoint](https://github.com/magicleap/SuperPointPretrainedNetwork). You just need to adapt `export_features.py` to take the SuperPoint model and weights instead of the one of LISRD, and then export the descriptors and compute the metrics with the same notebooks `hpatches_evaluation.ipynb` and `rdnim_evaluation.ipynb`.

**Comment by rpautrat** [comment]
I did not provide the source code to train on aachen in this repo, because I used the [code originally used in R2D2](https://github.com/naver/r2d2/blob/master/datasets/aachen.py). and I did not want additional dependencies. But you can use their code to create your own Aachen dataloader.

You can then fine-tune your existing model by adding the option `--resume_training_from <path to the pre-trained checkpoint>` in the training command.

**Comment by yakult98** [comment]
> I did not provide the source code to train on aachen in this repo, because I used the [code originally used in R2D2](https://github.com/naver/r2d2/blob/master/datasets/aachen.py). and I did not want additional dependencies. But you can use their code to create your own Aachen dataloader.
> 
> You can then fine-tune your existing model by adding the option `--resume_training_from <path to the pre-trained checkpoint>` in the training command.

ok, thanks for your reply!

**Comment by rpautrat** [comment]
I am closing this now, feel free to reopen it if you have more questions.
