### ISSUE TITLE
Hello, have you compared the time consumption of LISRD and SuperGlue?

### ISSUE THREAD

**Issue by yeluoo** [rpautrat/LISRD#18]
The time I measured is that LISRD is an order of magnitude less than the SuperGlue time, which makes me feel weird. I want to know the result of your comparison.

**Comment by rpautrat** [comment]
Hi, I haven't done a direct comparison, but yes, LISRD should be easily an order of magnitude faster than SuperGlue. The reason is that the backbone oft LISRD is a simple fully convolutional net and is very fast. On the contrary, SuperGlue needs to extract SuperPoint keypoints and descriptors (roughly same runtime as LISRD), then it performs matching in its GNN and solves the assignment with the Sinkhorn algorithm. These two additional steps are much slower.

**Comment by yeluoo** [comment]
Thank you
