### ISSUE TITLE
Hpatches

### ISSUE THREAD

**Issue by 2228186028** [rpautrat/LISRD#5]
Hello，I am learning your code.  I didn't find your code about table 2(Comparison to the state of the art on HPatches). I hope to get your code and data set about this part.   thank you very much!!!

**Comment by rpautrat** [comment]
Hi,
The code for HPatches evaluation is indeed not online for now. Before releasing it, I would need to clean it and to re-run some methods and this will take some time. Unfortunately, I don't think I will have time to do it before the CVPR deadline in a month...
But otherwise you can find the HPatches dataset here: https://github.com/hpatches/hpatches-dataset at least. I'll try to push the dataloader for this dataset after the CVPR deadline.

**Comment by 2228186028** [comment]
OK , Thank you very much！！！

**Comment by rpautrat** [comment]
Hi,

I finally found some time to add the processing and evaluation of the HPatches dataset. You can find the data loader in [`lisrd/datasets/hpatches.py`](https://github.com/rpautrat/LISRD/blob/master/lisrd/datasets/hpatches.py) and the evaluation notebook in [`notebooks/hpatches_evaluation.ipynb`](https://github.com/rpautrat/LISRD/blob/master/notebooks/hpatches_evaluation.ipynb). Note that the numbers in this notebook do not correspond exactly to the ones in the original papers, as they were obtained with SuperPoint keypoints and a different training.

Let me know if you encounter issue with it!

**Comment by zzkslam** [comment]
Hello, When I am running your evaluation notebook in notebooks/hpatches_evaluation.ipynb, I get the error: No such file or directory: '/home/victor/LISRD/Documents/datasets/Hpatches_sequences/i_nijmegen/1.ppm.kornia_sift'. Where can I get these pictures?

**Comment by rpautrat** [comment]
Hi,
Please find the answer in your other issue https://github.com/rpautrat/LISRD/issues/7#issuecomment-757790550.
